#!/bin/bash

main() {
  if [ "$1" = "--all" ]; then
    set -- $(list_all_binaries)
  fi
  if [ $# -eq 0 ]; then
    echo "Usage: $0 [--all|BIN...]"
    exit 1
  fi
  for bin; do
    local sep='*************'
    printf '%s\n** %s\n%s\n' "$sep" "$bin" "$sep"
    cargo run --bin "$bin" < data/$bin/input
  done
}

list_all_binaries() {
  for bin in src/bin/*; do
    basename -s .rs "$bin"
  done
}

main "$@"
